/**
 * tts.ts — Text-to-Speech generation.
 *
 * Engines (in order of recommendation):
 *   1. edge-tts (FREE) — Microsoft Edge voices via CLI, excellent quality
 *      Install: pip install edge-tts (or npx edge-tts)
 *   2. Coqui TTS (FREE, open-source) — local neural TTS
 *      Install: pip install TTS
 *   3. OpenAI TTS (PAID) — highest quality, $15/1M chars
 *      Needs: OPENAI_API_KEY
 */

import { execFile } from 'child_process';
import { promisify } from 'util';
import { existsSync, mkdirSync, readFileSync } from 'fs';
import { writeFile } from 'fs/promises';
import path from 'path';
import { config } from '../config.js';
import { moduleLogger } from '../utils/logger.js';
import { withRetry } from '../utils/retry.js';
import type { ShortScript, TTSResult, CaptionWord } from '../types/index.js';

const execFileAsync = promisify(execFile);
const log = moduleLogger('tts');

// ── VTT Parser ─────────────────────────────────────────────────────────────

/**
 * Parse a VTT/SRT subtitle file (generated by edge-tts --write-subtitles)
 * into word-level timing data.
 *
 * Note: edge-tts on Windows generates SRT format (comma decimal separator,
 * numbered cues) despite the .vtt extension. This parser handles both formats.
 */
function parseVTT(vttPath: string): CaptionWord[] {
  if (!existsSync(vttPath)) return [];
  const raw = readFileSync(vttPath, 'utf-8');
  const captions: CaptionWord[] = [];

  // Match both VTT (dot) and SRT (comma) timestamp formats:
  //   VTT: 00:00:00.000 --> 00:00:01.200
  //   SRT: 00:00:00,100 --> 00:00:04,526
  const cuePattern = /(\d{2}:\d{2}:\d{2}[.,]\d{3})\s*-->\s*(\d{2}:\d{2}:\d{2}[.,]\d{3})\s*\n(.+)/g;
  let match;
  while ((match = cuePattern.exec(raw)) !== null) {
    const startMs = vttTimeToMs(match[1]);
    const endMs = vttTimeToMs(match[2]);
    const text = match[3].trim();
    if (text) captions.push({ text, startMs, endMs });
  }

  return captions;
}

function vttTimeToMs(ts: string): number {
  const [h, m, rest] = ts.split(':');
  // Handle both VTT (dot) and SRT (comma) decimal separators
  const [s, ms] = rest.split(/[.,]/);
  return (+h * 3600 + +m * 60 + +s) * 1000 + +ms;
}

// ── Engine: edge-tts (FREE, recommended) ───────────────────────────────────

/**
 * Generate TTS using Microsoft Edge TTS (free, high quality).
 *
 * Prerequisites:
 *   pip install edge-tts
 *   # or use npx: npx edge-tts --text "hello" --write-media out.mp3
 *
 * List voices: edge-tts --list-voices
 * Recommended voices:
 *   en-US-GuyNeural       (male, clear, warm)
 *   en-US-AriaNeural      (female, natural)
 *   en-GB-RyanNeural      (British male)
 *   en-US-ChristopherNeural (male, authoritative)
 */
async function generateEdgeTTS(text: string, outputPath: string, subtitlePath?: string): Promise<void> {
  const voice = config.tts.voice || 'en-US-GuyNeural';

  // edge-tts CLI: pip install edge-tts
  const args = [
    '--text', text,
    '--voice', voice,
    '--write-media', outputPath,
    ...(subtitlePath ? ['--write-subtitles', subtitlePath] : []),
    '--rate', '+5%',    // Slightly faster for Shorts pacing
    '--pitch', '+0Hz',  // Natural pitch
  ];

  log.info({ voice, outputPath }, 'Generating edge-tts audio');

  try {
    await execFileAsync('edge-tts', args, { timeout: 60000 });
  } catch (err) {
    // Fallback: try via Python module
    log.warn('edge-tts CLI failed, trying python -m edge_tts');
    await execFileAsync('python3', ['-m', 'edge_tts', ...args], { timeout: 60000 });
  }
}

// ── Engine: Coqui TTS (FREE, open-source, local) ──────────────────────────

/**
 * Generate TTS using Coqui TTS (runs locally, GPU recommended).
 *
 * Prerequisites:
 *   pip install TTS
 *
 * Good models:
 *   tts_models/en/ljspeech/tacotron2-DDC     (fast, decent)
 *   tts_models/en/vctk/vits                   (multi-speaker)
 *   tts_models/multilingual/multi-dataset/xtts_v2  (best quality, slow)
 */
async function generateCoquiTTS(text: string, outputPath: string): Promise<void> {
  const model = 'tts_models/en/ljspeech/tacotron2-DDC';

  const args = [
    '-m', 'TTS',
    '--text', text,
    '--model_name', model,
    '--out_path', outputPath,
  ];

  log.info({ model, outputPath }, 'Generating Coqui TTS audio');
  await execFileAsync('python3', args, { timeout: 120000 });
}

// ── Engine: ElevenLabs TTS ─────────────────────────────────────────────────

/**
 * Generate TTS using ElevenLabs API.
 *
 * Default voice: Adam (pNInz6obpgDQGcFmaJgB) — clear, authoritative male
 * Other good voices: Rachel (21m00Tcm4TlvDq8ikWAM), Clyde (2EiwWnXFnvU5JabPnv8n)
 * Docs: https://api.elevenlabs.io/docs
 */
async function generateElevenLabsTTS(text: string, outputPath: string): Promise<void> {
  const apiKey = config.elevenlabs.apiKey;
  if (!apiKey) throw new Error('ElevenLabs API key required');

  const voiceId = config.tts.elevenLabsVoiceId ?? 'pNInz6obpgDQGcFmaJgB'; // Adam

  log.info({ voiceId, outputPath }, 'Generating ElevenLabs TTS audio');

  const resp = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'xi-api-key': apiKey,
    },
    body: JSON.stringify({
      text,
      model_id: 'eleven_turbo_v2', // Fast & high quality; use 'eleven_multilingual_v2' for premium
      voice_settings: {
        stability: 0.5,
        similarity_boost: 0.75,
        style: 0.0,
        use_speaker_boost: true,
      },
    }),
  });

  if (!resp.ok) {
    const err = await resp.text();
    throw new Error(`ElevenLabs TTS failed: ${resp.status} — ${err}`);
  }

  const buffer = Buffer.from(await resp.arrayBuffer());
  await writeFile(outputPath, buffer);
}

// ── Engine: OpenAI TTS (PAID, highest quality) ─────────────────────────────

/**
 * Generate TTS using OpenAI's TTS API.
 *
 * Cost: ~$15 per 1M characters (tts-1), ~$30 per 1M (tts-1-hd)
 * Voices: alloy, echo, fable, onyx, nova, shimmer
 */
async function generateOpenAITTS(text: string, outputPath: string): Promise<void> {
  const apiKey = config.openai.apiKey;
  if (!apiKey) throw new Error('OpenAI API key required for OpenAI TTS');

  const voice = config.tts.openaiVoice || 'onyx';

  log.info({ voice, outputPath }, 'Generating OpenAI TTS audio');

  const resp = await fetch('https://api.openai.com/v1/audio/speech', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: 'tts-1',       // Use 'tts-1-hd' for higher quality
      input: text,
      voice,
      response_format: 'mp3',
      speed: 1.05,           // Slightly faster for Shorts
    }),
  });

  if (!resp.ok) {
    const err = await resp.text();
    throw new Error(`OpenAI TTS failed: ${resp.status} — ${err}`);
  }

  const buffer = Buffer.from(await resp.arrayBuffer());
  await writeFile(outputPath, buffer);
}

// ── Get Audio Duration ─────────────────────────────────────────────────────

async function getAudioDuration(filePath: string): Promise<number> {
  try {
    const { stdout } = await execFileAsync(config.paths.ffprobe, [
      '-v', 'error',
      '-show_entries', 'format=duration',
      '-of', 'csv=p=0',
      filePath,
    ]);
    return parseFloat(stdout.trim());
  } catch {
    // Fallback: estimate from file size (rough: 16kbps mp3 ≈ 2KB/s)
    log.warn('ffprobe failed, estimating duration from file size');
    const { statSync } = await import('fs');
    const bytes = statSync(filePath).size;
    return bytes / 2000; // Very rough estimate
  }
}

// ── Main TTS Entry Point ──────────────────────────────────────────────────

/**
 * Generate voiceover audio for the given script.
 * Uses the configured TTS engine with automatic fallback.
 */
export async function generateTTS(
  script: ShortScript,
  word: string,
  wordId: string
): Promise<TTSResult> {
  const wordDir = path.join(config.paths.output, 'words', word);
  mkdirSync(wordDir, { recursive: true });
  const outputPath = path.join(wordDir, 'tts.mp3');
  const subtitlePath = path.join(wordDir, 'tts.vtt');
  const text = script.fullText;

  log.info({ engine: config.tts.engine, wordId, textLength: text.length }, 'Starting TTS');

  // Engine selection with fallback chain
  // edge-tts calls include subtitlePath for word-level timing
  const engines: Array<{ name: string; fn: () => Promise<void> }> = [];

  switch (config.tts.engine) {
    case 'openai':
      engines.push(
        { name: 'openai', fn: () => generateOpenAITTS(text, outputPath) },
        { name: 'elevenlabs', fn: () => generateElevenLabsTTS(text, outputPath) },
        { name: 'edge-tts', fn: () => generateEdgeTTS(text, outputPath, subtitlePath) },
      );
      break;
    case 'elevenlabs':
      engines.push(
        { name: 'elevenlabs', fn: () => generateElevenLabsTTS(text, outputPath) },
        { name: 'edge-tts', fn: () => generateEdgeTTS(text, outputPath, subtitlePath) },
      );
      break;
    case 'coqui':
      engines.push(
        { name: 'coqui', fn: () => generateCoquiTTS(text, outputPath) },
        { name: 'elevenlabs', fn: () => generateElevenLabsTTS(text, outputPath) },
        { name: 'edge-tts', fn: () => generateEdgeTTS(text, outputPath, subtitlePath) },
      );
      break;
    default: // edge-tts
      engines.push(
        { name: 'edge-tts', fn: () => generateEdgeTTS(text, outputPath, subtitlePath) },
        { name: 'elevenlabs', fn: () => generateElevenLabsTTS(text, outputPath) },
        { name: 'coqui', fn: () => generateCoquiTTS(text, outputPath) },
      );
  }

  let usedEngine = '';
  for (const engine of engines) {
    try {
      await withRetry(engine.fn, `tts:${engine.name}`, { maxAttempts: 2 });
      usedEngine = engine.name;
      break;
    } catch (err) {
      log.warn({ engine: engine.name, error: (err as Error).message },
        'TTS engine failed, trying next');
    }
  }

  if (!usedEngine) {
    throw new Error('All TTS engines failed');
  }

  // Get actual duration
  const durationSec = await getAudioDuration(outputPath);

  // Parse word-level captions from VTT (edge-tts generates these)
  const captions = parseVTT(subtitlePath);
  if (captions.length > 0) {
    log.info({ captionCount: captions.length }, 'Parsed word-level captions from VTT');
  }

  log.info({ engine: usedEngine, durationSec, outputPath }, 'TTS complete');

  return {
    audioPath: outputPath,
    durationSec,
    engine: usedEngine,
    subtitlePath: existsSync(subtitlePath) ? subtitlePath : undefined,
    captions: captions.length > 0 ? captions : undefined,
  };
}
